### ISSUE TITLE
Add regex rule for service-info type `artifact` values

### ISSUE THREAD

**Issue by jaeddy** [ga4gh/TASC#13]
Following on #4, we should document restrictions for the string formatting of service type names (i.e., `artifact` values). For example, if we agree on kabob-case, the regex pattern to enforce would be:

`"^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"`

Ultimately, this is something that the [**service-info**](https://github.com/ga4gh-discovery/ga4gh-service-info) API can include in the OAI spec for validation purposes.

**Comment by jaeddy** [comment]
Here's the current set of services, for reference:
https://github.com/ga4gh/TASC/blob/master/service-info/ga4gh-service-info.json

**Comment by jb-adams** [comment]
this pattern states that a dash cannot be the first character, but is it also saying a dash cannot be the last character? If not, I think that should be included. Also, I might advocate for excluding numbers from `artifact` (to me they belong in the `version`) unless there's a good reason for keeping them in.

**Comment by jmarshall** [comment]
Most of the complexity of the RE comes from what it's saying about hyphens: they can't be first, last, or two of them adjacent anywhere. :+1: from me on that.

Presumably the suggestion allows non-first digits so as to allow for the possibly of services like `foo2bar`, e.g., `b2b`, or similar.

**Comment by rrfreimuth** [comment]
+1 from me

**Comment by jb-adams** [comment]
+1 from me
