### ISSUE TITLE
Protocol version number bumps due to service-info response changes

### ISSUE THREAD

**Issue by jmarshall** [ga4gh/TASC#17]
Does TASC have any advice it would like to provide as to whether semantic versioning as used by GA4GH requires a major version bump for a change that is incompatible but only affects a minor non-core part of a protocol's functionality?

----

In detail:

Refget has a PR in progress (PR samtools/hts-specs#479) that adds a `ga4gh` hashing scheme name to the protocol (in a backwards compatible manner) and implements the GA4GH-standardised `/sequence/service-info` endpoint rather than the previous pre-standardisation serviceinfo on the same endpoint.

The changes to the main refget protocol add an additional possible value for a JSON member field, but the schema is unchanged and there are no protocol compatibility concerns for older clients.

The serviceinfo change changes the schema of the JSON response to a `/sequence/service-info` request. The previous response was similar to:

```json
{ "service": {
     "circular_supported" : false,
     "algorithms": ["md5", "trunc512"],
     "subsequence_limit": 4000000,
     "supported_api_versions": ["1.0"]
     }
}
```

The new response is the usual standardised service-info with a `refget` field:

```json
{ "id": "org.ga4gh.refget",
  "name": "Refget server",
  "type": { "group": "org.ga4gh", "artifact": "refget", "version": "x.y.z" },
  "description": "Reference sequences from checksums",
  "…": "…",
  "refget": {
     "circular_supported": true,
     "subsequence_limit": 0,
     "algorithms": [ "…" ]
     }
}
```

On the face of it, this is an incompatible change for the serviceinfo endpoint so Semantic Versioning would suggest a major version bump. (Though it should be noted that the two response JSON structures are easily and unambiguously recognisable.)

On the other hand, the bulk of the protocol is unchanged: the additions to the actual **refget** important parts of the protocol warrant at most a minor version bump. Users and implementors seeing “refget 2.0.0” would be misled into thinking a “refget 2.0 server” represented a significant incompatibility for their application.

[CC @andrewyatz @jb-adams]

**Comment by jmarshall** [comment]
In terms of [SemVer](https://semver.org), this comes down to: What constitutes the _Public API_? 

Does the refget public API encompass the set of endpoints that are the heart of refget and truly refget-specific? Or does it also include — as a first-class item that's equally fundamental to refget — the service-info endpoint that's on the side?

**Comment by andrewyatz** [comment]
Thanks for the cc @jmarshall and yes I agree with you this is how we view the service-info component's inclusion in the refget spec.

**Comment by rrfreimuth** [comment]
As mentioned during the TASC call today, if the current API were extended to support the new return structure when an optional query parameter were used (default behavior is to return the current structure), then the semver/breaking change issues might be avoided.  The default behavior of the API can be changed at the next major release.

**Comment by jmarshall** [comment]
To summarise my recollection of the discussion of this on a previous TASC call:

General agreement that it would be desirable and appropriate to avoid a major version bump in this situation. Desirable for implementations to be able to return either response format as selected by refget version numbers specified in client requests' `Accept` headers. General agreement with @rrfreimuth's comment above.
