### ISSUE TITLE
GitHub Integrations & Security concerns

### ISSUE THREAD

**Issue by rishidev** [ga4gh/TASC#20]
The following was recieved from Reece Hart. It may require recommendations from TASC, or passed on for Data Security to give advice. Some scoping e.g. GA4GH specs vs Software might be required also to deal with this

I just got this request from Slack to approve an integration. We get these from time to time in slack and on github.
A github integration I use was just hacked. This permitted users to gain access. Fortunately, the scope was read only and my repos are all public.
I'm forwarding to you because I think this is a place for TASC to get involved. There are lots of admins on services, and I'm unconvinced that everyone understands the risks that they might be creating. For example, it is possible in principal to grant permissions to delete repos, which could be very problematic.
All FYI. You can decide whether TASC should be involved.

**Comment by rishidev** [comment]
At the discussion it was thought this was something more for Data Security to comment, and for GA4GH Secretariat to manage (through a Security Expert or Technical Team) due to the depth of involvement required.

**Comment by davidbernick** [comment]
Yes the "scopes" requested by the integrations, the integration application security posture and the use of 2FA on all our accounts should all be considered. Maybe I'll just crib Broad's security posture for Github and propose that as something official.
