### ISSUE TITLE
Service Info type list

### ISSUE THREAD

**Issue by rishidev** [ga4gh/TASC#4]
The Service Info endpoint has a type field to clarify what the service is. For GA4GH based items it is suggested that this is submitted as part of the Product Approval Process and looked at by the TASC team. FURTHER CLARIFICATION: This is meant to be a list, managed by the TASC group. It is not meant to provide tracking of version attribute of the type field.

**Comment by jb-adams** [comment]
@andrewyatz @mcupak I think this is what we discussed on the Networks Call.

Rishi, my understanding is that we essentially want to "subclass" the service-info response according to service type. So, the base Service has attributes: `id, name, type, description, organization, version` etc., but different service types might require additional attributes.

e.g. refget has the specific additional attributes `circular_supported, algorithms, subsequence_limit` that are important in informing the client how the service works.

The service-info type registry would clarify the accepted `type` value for each service type, as well as additional attributes unique to each service type.

Does that sound accurate?

**Comment by mcupak** [comment]
@jb-adams I think what this issue is about is prescribing what the type field should be for approved standards. I think your description of how a multi-type service registry should work is exactly right, service-info is extensible in that sense and we'd expect the custom attributes to propagate to the registry as well, and I think using the registry could be one way of exposing the types (through the /types endpoint).

There are other options, here are other relevant things Ian and @andrewyatz mentioned today, for reference:
- http://identifiers.org/ (http://n2t.net/)
- https://vr-spec.readthedocs.io/en/1.0/impl-guide/computed_identifiers.html#identify

**Comment by ianfore** [comment]
[This paper](https://www.nature.com/articles/sdata201829) adds additional context on identifiers.org and n2t.net

Haven't looked much further at the vr-spec but I did notice that 
> The GA4GH schema MAY be used with identifiers from any namespace. For example, a SequenceLocation may be defined using a sequence_id = refseq:NC_000019.10. 

That suggests that the curie scheme may have been taken into account. refseq is registered and the identifier, exactly as given, should resolvable by the two named resolvers 
By identifiers.org [refseq:NC_000019.10](http://identifiers.org/refseq:NC_000019.10)
By n2t.net [refseq:NC_000019.10](http://n2t.net/refseq:NC_000019.10)

**Comment by andrewyatz** [comment]
Reece did look into this a lot but yes the idea is that other identifiers can be used in that position.

**Comment by andrewyatz** [comment]
@jb-adams this is more about standardisation of the type field as stated by @mcupak. Subclassing is something that should be left to the service and shouldn't worry us here.

**Comment by jb-adams** [comment]
Right makes sense, the particular `/service-info` properties for each service type will be handled by that type's OAI spec.

Ok, I'll put a table together for TASC to review

**Comment by rishidev** [comment]
We probably need an initial higher level PR than what has been proposed documenting what the process is for accepting the GA4GH API Service Info types.

So it should probably say

1. there will be a JSON file, and a TSV file with an example for each

2. Some guidelines on acceptable name suggestions. I think the uppercase nature in RNAget was something to clarify here.

3. Then the process should be individual PRs to the newly created TSV/JSON files proposed by the teams.

I will craft something up for this

**Comment by jaeddy** [comment]
Based on some of the discussion in this morning's call, it might be worth renaming this issue (or at least clarifying somewhere in the comments) that the goal of TASC is to establish a **controlled vocabulary** for `artifact` values (e.g., `"wes", `"refget"`). We're not actually creating a registry of services (like [this project](https://github.com/ga4gh-discovery/ga4gh-service-registry)).

**Comment by mcupak** [comment]
I like @susheel 's suggestion from the call today re including URLs to the specification repos. It seems that effectively what we need is a tuple of artifact ID and URL, and a fixed group ID to use for everything. We could add URLs here, or do it the other way round - only maintain a list of URLs to repos, and ask people to include a file with the artifact ID etc. as part of the product approval process (regardless of how we do it, it would be useful to have the artifact ID referenced in the original repos somehow for easy implementation).
