### ISSUE TITLE
Clarification request: What constitutes an API breaking change?

### ISSUE THREAD

**Issue by uniqueg** [ga4gh/TASC#47]
During the [TES](https://github.com/ga4gh/task-execution-schemas) working meeting, we recently had a debate on what would constitute a breaking change requiring a major version bump. Two options:

1. Only changes that make old clients (e.g., for 1.0.0 servers) incompatible with new servers (e.g., 2.0.0) constitute breaking changes.
2. In addition to 1., also changes that make new clients (e.g., for 2.0.0 servers) incompatible with old servers (e.g., 1.0.0) constitute breaking changes.

During the discussion, we all felt (@vsmalladi, @kellrott, @MattMcL4475) that type 2. incompatibilities are less critical and could be solved through client/server negotiation (check server version in service info and use appropriate client version) and therefore maybe shouldn't require major version bumps.

However, it is a matter of policy, and it would be good to have clarification on this issue.

A bit of context, as a reminder: Major version bumps require paperwork, a security evaluation and SC approval - a tedious process that API champions try to avoid whenever possible. This reluctance can slow down or even halt spec development, possible leading to a drop in adoption. On the other hand, we of course don't want to make breaking changes too easy, as it can lead to a fragmentation of the implementer space and ultimately also lead to a drop in adoption.

**Comment by denis-yuen** [comment]
Superficially, I would think I agree. Probably missing something, but isn't type 2 basically a minor version bump as in 
```
MINOR version when you add functionality in a backward compatible manner
```
https://semver.org/

i.e. it makes sense that if you add a new feature in a minor version, clients that rely on that new feature wouldn't be able to use it in older versions of the server. But that should not cause a major bump

**Comment by uniqueg** [comment]
Hmm. I really should have included the example we were discussing. Because now I don't remember it anymore 😅

But yeah, it's possible that we were all confused on this.

Let's see if I stumble over the example again, or perhaps the others remember it. I'll close the issue for now.
