### ISSUE TITLE
Make standards information more findable

### ISSUE THREAD

**Issue by mcupak** [ga4gh/TASC#7]
It would be good if we could increase findability of GA4GH standards across workstreams. While [officially approved standards are easy to find](https://www.ga4gh.org/genomic-data-toolkit/), standards that are work in progress are a bit more of a challenge.

The issue is two-fold - how do I find the specs that are relevant for me, and how do I find their docs.

For specifications, there are a number of GH organizations that don't necessarily map to workstreams/projects (e.g. ga4gh-beacon for the Beacon Project, ga4gh-discovery for Discovery WS except Beacon, ga4gh for effectively the Cloud WS?). Within organizations, it's still not easy to see which repositories are standards vs. other tools (e.g. https://github.com/ga4gh). Maybe have some sort of a catalog/labelling?

For docs, it would be nice if there was more consistency. We're using different formats (e.g. [Discovery](https://ga4gh-discovery.github.io/), [Cloud](https://github.com/ga4gh/wiki/wiki)), and the information is usually split between some page and individual GH repos. Maybe we can have some sort of a central website with docs or links to docs?

**Comment by jb-adams** [comment]
@mcupak I think GA4GH would benefit from this a lot. I had an idea of the "Standards Lookup API" we discussed serving as an underlying layer for some sort of "standards explorer" web interface.

It could capture the following information about each standard:
- basic metadata (name, version(s), etc.)
- status (approved, proposed, no longer supported, etc.)
- link to OAI spec (the .yaml file and/or repository containing the spec)
- link to human-readable documentation
- semantic tags/labels so newcomers can filter by what standards are relevant to their use case

An explorer UI/website could be built on top of this, serving as a centralized location for all standards (essentially one-click away from any standard). This would let teams continue to develop in any Github org, while still making sure all GA4GH outputs are accessible from a common location.

Is this something along the lines of what you're thinking?

**Comment by mcupak** [comment]
Thanks @jb-adams, sounds like that would certainly help with the first part of the issue (repos), and what you're proposing is more sophisticated than what I was thinking about. I'm looking specifically for findability of specifications and projects that are under development for use within GA4GH and didn't realize your API would deal with this as well, that's great!

For the docs part, if we can't have everything in one place, I think it could be useful to provide a deployable template to use.

**Comment by rishidev** [comment]
I think the part that Jeremy is discussion is based on Issue #1.

The website part is something to discuss maybe
